### ISSUE TITLE
fix: merge generates an empty page on some pdfs

### ISSUE THREAD

**Issue by lajp** [Tietokilta/laskugeneraattori#29]
Some PDFs (generated by Microsoft Word) cause the merge to create an emtpy page for them with no content

**Comment by IiroP** [comment]
In the example file (not public), the issue is caused by one extra whitespace character. More specifically, in
`<< /Length 2396 /Filter /FlateDecode >> stream`  there is one whitespace character after `stream` keyword. This causes `lopdf` to skip reading the stream (which contains the main content of the file). 

According to the PDF standard (in this case 1.3 version), 

> The keyword stream that follows the stream dictionary should be followed by either a carriage return and a line feed or by just a line feed, and not by a carriage return alone. 

Which makes it questionable if the extra whitespace character is even allowed, or just tolerated by most programs. For example `qpdf` tool issues warning about that whitespace. 

This PDF in question was created by Microsoft Reporting Services 10.0.0.0, and [others](https://sources.debian.org/patches/pdftk/1.44-7/fix_infinite_loop_on_lf_eol/) have also had similar issues with those PDF:s

**Comment by lajp** [comment]
Hi, good job with this! I'll take a closer look at this.

**Comment by IiroP** [comment]
> Hi, good job with this! I'll take a closer look at this.

Great :+1:  The relevant parsing seems to happen on `lopdf` at file `nom_parser.rs` at [`stream` function](https://github.com/J-F-Liu/lopdf/blob/80b3e7391f204de1f7e03f1e5f1560e724ba4aeb/src/nom_parser.rs#L313).
